### ISSUE TITLE
`__constants__` and `__expressions__` sections

### ISSUE THREAD

**Issue by beckermr** [koesterlab/yte#12]
It'd be nice to support very limited forms of this like this

```
__constants__:
  blah: 1

__expressions__:
  blahblah: ?f"{blah}{blah}"
```

This is an issue that came out of discussions on gitter.
